### PR TITLE
Color changes in website #36

### PR DESCRIPTION
**Pull request by harshita214**
Changes done as shown in PR #36

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@harshita214 Don't make PR for a single line change, please. For the same issue, you have made two PRs with very small changes. Please make commits to a single PR instead of creating new ones for every commit.

**Comment by harshita214** [comment]
Sir, I made 2 PR for a reason that is for the main background the styling was done in HTML but the rest styling was in Style.css so  I did it and made 2 PR's instead of one, the UI is the same as referred to in #36. Also, I didn't want to disrupt the code so changed it there only.#43 is the PR responsible for background color change while #36 for the rest, I can assure you they both are not duplicate of each other.

**Comment by ExpressHermes** [comment]
@harshita214 You can use the same PR to do different changes. The second PR was a single-line change. Use this PR for doing both the changes.

**Comment by harshita214** [comment]
I have made a new PR for the same, where a preview can also be seen. This PR can be closed now.

**Pull request closed without merging**
